---
name: MacOS

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        cxx: [clang++, g++-15]

    steps:
      - uses: actions/checkout@v5

      - uses: actions/cache@v4
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Install python
        run: brew install llvm clang-format python pipx

      - name: Install builddriver
        run:
          pipx install builddriver cmake_format==0.6.11 pyaml

      - name: configure
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DBOOST_UT_ENABLE_RUN_AFTER_BUILD=NO \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON --log-level=DEBUG -DFETCHCONTENT_QUIET=OFF -DCMAKE_CXX_COMPILER=${{matrix.cxx}}

      - name: build
        run: cmake --build build -j4 --verbose

      - name: test
        run: ctest --test-dir build --build-config Debug -j4 --verbose

      - name: Run clang-tidy
        if: matrix.cc == 'clang'
        shell: bash
        run: |
          export PATH=$(brew --prefix llvm)/bin:${PATH}
          $(brew --prefix llvm)/bin/run-clang-tidy \
            -p build test 2>&1 | tee .run-clang-tidy.log
          builddriver cat .run-clang-tidy.log
